server:
  servlet:
    context-path: '/api/'
  error:
    include-message: always
  port: ${PORT:8888}
  address: 0.0.0.0

application:
  feign-api:
    extra_values_user_api: https://mxsmcv2cx7zlcq4xngqw2a7y3y0osmfi.lambda-url.eu-central-1.on.aws/
    extra_values_api: http://ec2-63-178-189-113.eu-central-1.compute.amazonaws.com/api-usb
    calculate_benf_api: https://pumoe7ivke.execute-api.eu-central-1.amazonaws.com/default
    generate_push_api: https://uuwoerh67eiacwozhkgolfrayu0tdtex.lambda-url.eu-central-1.on.aws
## https://github.com/camunda-community-hub/spring-zeebe

spring:
  data:
    mongodb:
      uri: mongodb://user_qit:123@localhost:27017/?maxPoolSize=100
      database: kzh
      auto-index-creation: true

camunda:
  client:
    zeebe:
      request-timeout: 360s
      base-url: ${ZEEBE_BASE_URL:http://localhost:8088}
      gateway-url: ${ZEEBE_GATEWAY_URL:http://localhost:26500}
    operate:
      base-url: ${OPERATE_BASE_URL:http://localhost:8081}
      username: demo
      password: demo
      auth-enabled: false

logging:
  level:
    org:
      hibernate:
        type: debug
        stat: debug



